Fix custom messages in comparison-assertions
stretchr/testify pull request #1021
Opened 2020-11-05 02:58 UTC by benjaminjkraft

## Summary
This PR fixes custom messages in comparison-assertions.

## Changes
The assesrtions now pass varargs rather than a single slice arg.

## Motivation
The comparison-assertions were passing msgAndArgs as a slice rather than
varargs, which meant that the entire message-and-arguments got printed
as a single slice.  Now it gets printf-ed correctly.

2021-01-14 11:30 UTC, boyan-soubachov requested changes
Looks great, thanks for catching this! Is it possible to add a test to cover the regression caused by not expanding the varargs?

2021-01-22 02:15 UTC, benjaminjkraft commented
Hi @boyan-soubachov -- thanks for the look!  The test I added should cover the regression, I think -- if you run it without the other changes it fails with e.g.
```
    assertion_compare_test.go:266: 
                Error Trace:
                Error:          "\n\tError Trace:\t\n\tError:      \t\"1\" is not greater than \"2\"\n\tMessages:   \t[%v wasn't greater 1]\n" does not contain "1 wasn't greater"
                Test:           TestComparisonCustomMessages
```
Let me know if there was something different you wanted, I'm happy to add it!

2021-04-09 02:40 UTC, codyohlsen commented
can we merge this? :) thanks

2021-05-19 19:28 UTC, AlekSi commented
@boyan-soubachov PTAL

2022-04-21 21:11 UTC, lambdanis commented
Looks like the issue was fixed in https://github.com/stretchr/testify/pull/1150/, so this PR can be closed.

2024-03-06 01:23 UTC, dolmen commented
@benjaminjkraft Thanks for the patch. Unfortunately it hasn't been noticed earlier.

@lambdanis Thanks for the duplicate report.

2024-03-06 01:23 UTC, closed without merging