Not error as
stretchr/testify pull request #1129
Opened 2021-11-30 13:40 UTC by palsivertsen

## Summary
The library had implementations for ErrorIs, ErrorAs and NotErrorIs but
was missing a NotErrorAs implementation. This PR adds a NotErrorAs
function, which is the inverse of the ErrorAs function.

## Changes
* Adds `NotErrorAs` function and test
* Improves existing tests (`TestErrorIs`, `TestNotErrorIs` and `TestErrorAs`) by comparing assertion result and `testing.T` flag.
* Clarifies documentation for existing `NotErrorIs` function

## Motivation
There's already an inverse of `ErrorIs`, `ErrorAs` should have an inverse as well.

## Related issues

Closes #1066

2023-09-05 05:06 UTC, Antonboom commented
+1 for this PR.
and take a look to https://github.com/stretchr/testify/pull/1137

2024-10-03 16:10 UTC, brackendawson commented on assert/assertion_forward.go
> +// This is the inverse of the ErrorAs function.
This file is generated.

2024-10-03 16:12 UTC, brackendawson commented
Commented on @mmorel-35 's review. This also needs a re-base. This also needs coordinating with #1646.

2024-10-04 08:16 UTC, palsivertsen commented
@brackendawson Rebased on master and addressed review feedback. Also fixed a typo.

2024-10-04 10:10 UTC, brackendawson requested changes
Sorry for the tennis, one more change to that doc-string. I think this slightly left field behaviour needs writing down.

2024-10-04 12:38 UTC, brackendawson approved these changes
LGTM, thank you for your contribution.

2024-10-04 12:38 UTC, merged