Ensure AssertExpectations does not fail in skipped tests
stretchr/testify pull request #1331
Opened 2023-01-27 19:27 UTC by ianrose14

## Summary

Prevent `(*Mock).AssertExpectations` from failing if test expectations are not met but the test has already been marked as "Skipped".

## Changes
* Add check to `(*Mock).AssertExpectations` such that if the `*testing.T` is already marked skipped, we just return true immediately.
* Add a unit test (`Test_Mock_AssertExpectations_Skipped_Test`) for the new behavior.

## Motivation
Normally the decision to skip a test is made early in the test function, but on occasion it might be the case that you have already set up some mock expectations _before_ you call `t.Skip`.  If that's the case, then a call to `AssertExpectations` will fail, which is not intended.

## Example usage (if applicable)
```go
func TestExample(t *testing.T) {
	val := new(MockedValue)
	val.On("DoThing", 1, 2).Return(3, 4)
	defer val.AssertExpectations(t)

	if os.GetEnv("foo") == "" {
		// This will cause the test to exit, which will run the deferred AssertExpections call above
		t.Skip("nevermind")
	}
	...
}
```

## Related issues
Closes https://github.com/stretchr/testify/issues/1329

2023-02-03 10:30 UTC, brackendawson commented
Thanks for the PR, I'd love to see this merged.

2023-07-06 10:04 UTC, dolmen approved these changes

2023-07-06 10:05 UTC, dolmen commented
@ianrose14 Could you rebase your branch on top of master (and fix conflicts)?

2023-07-07 19:05 UTC, ianrose14 commented
> @ianrose14 Could you rebase your branch on top of master (and fix conflicts)?

done!

2023-07-25 00:09 UTC, dolmen requested changes

2023-07-25 00:09 UTC, dolmen commented on mock/mock.go
> +		if s.Skipped() {
Merge this condition in the check above:

```go
ok && s.Skipped()
```

2023-07-29 03:46 UTC, dolmen commented
Please squash commits.

2023-08-06 13:35 UTC, ianrose14 commented
> Code looks good.
> 
> Please squash commits.

@dolmen done!

2023-10-30 22:59 UTC, dolmen approved these changes

2024-02-17 17:50 UTC, brackendawson approved these changes
Thank you for your contribution.

2024-02-17 17:50 UTC, merged