Support pointer on top-level for 'TestEqualExportedValues' & Get rid of duplicate 'ObjectsExportedFieldsAreEqual'
stretchr/testify pull request #1384
Opened 2023-05-19 19:59 UTC by HaraldNordgren

2023-05-19 20:27 UTC, HaraldNordgren commented
Ping @boyan-soubachov

2023-05-19 20:32 UTC, HaraldNordgren commented
Ping @boyan-soubachov @mchlp @feidtmb

2023-05-21 05:25 UTC, mchlp approved these changes

2023-06-18 16:30 UTC, HaraldNordgren commented
Ping @boyan-soubachov 

This will improve the user experience for `TestEqualExportedValues`.

2023-06-28 09:27 UTC, HaraldNordgren commented
Ping @boyan-soubachov

Currently the library is usable, but it gives this error when comparing Protobuf objects because you have to access the underlying pointer, otherwise the comparison is false:

```
call of assert.EqualExportedValues copies lock value: github.com/dietdoctor/genproto/go/my-project/v1.ListItemsResponse contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutexcopylocks
```

2023-07-29 03:23 UTC, dolmen requested changes
> I am also getting rid of the duplicated `ObjectsExportedFieldsAreEqual`

While this looks sane, this is not that easy. We have to preserve the API surface. Please keep the function and mark it as `// Deprecated:`.

2023-07-29 03:31 UTC, dolmen requested changes

2023-07-29 03:31 UTC, dolmen commented on assert/assertions_test.go
>  				t.Errorf("ObjectsExportedFieldsAreEqual(%#v, %#v) should return %#v", c.expected, c.actual, c.result)
The message prefix must be fixed.

2023-07-29 19:44 UTC, HaraldNordgren commented
@dolmen Done, I have update the code! 🤗

2023-08-10 03:36 UTC, jufemaiz commented
👀

2023-08-11 08:49 UTC, HaraldNordgren commented
@dolmen Hi, did you have time to take another look at this?

2023-09-07 08:44 UTC, HaraldNordgren commented
Hi @dolmen @boyan-soubachov, did you have a chance to take a look at this?

2023-09-17 21:45 UTC, boyan-soubachov submitted a review, later dismissed
LGTM, thank you

2023-10-16 12:41 UTC, dolmen requested changes
Please open a separate MR to deprecate `ObjectsExportedFieldsAreEqual`, and move that change there.

Also cleanup commits, and rebase (do not merge master into your branch!).

2023-10-16 13:55 UTC, HaraldNordgren commented
@dolmen Done!

2023-10-16 16:42 UTC, dolmen approved these changes
Ready for v1.9.0: this is a behaviour change that require a minor release.

2024-01-11 19:09 UTC, HaraldNordgren commented
@dolmen Any update on when 1.9.0 is expected? Let's merge this in the meantime?

2024-02-10 10:17 UTC, HaraldNordgren commented
Ping @dolmen

2024-02-23 13:11 UTC, brackendawson commented
I think #1517 fully implemented this.

2024-02-23 13:11 UTC, closed without merging