code optimization
stretchr/testify pull request #1386
Opened 2023-05-25 01:42 UTC by testwill

io/ioutil deprecated etc.

2023-05-30 09:53 UTC, ozkansen approved these changes

2023-07-04 08:30 UTC, dolmen requested changes

2023-07-04 08:30 UTC, dolmen commented on mock/mock.go
> +	re := regexp.MustCompile(`\.pN\d+_`)
This change is not needed. This is just a quotes changes. While I agree that it improves redability, it has nothing to do in a MR that claims "code optimization". Please make a separate MR.

2023-07-04 08:30 UTC, dolmen commented on mock/mock_test.go
> +	assert.Regexp(t, regexp.MustCompile(`(?s)FAIL: 0 out of 1 expectation\(s\) were met.*The code you are testing needs to make 1 more call\(s\).*`), tcl.errs[0])
This changes quoting. This is an unrelated change.

2023-07-04 08:30 UTC, dolmen commented on mock/mock_test.go
> +	assert.Regexp(t, regexp.MustCompile(`(?s)FAIL:\tGetTime\(int\).*`), tcl.logs[0])
This changes quoting. This is an unrelated change.

2023-07-04 08:30 UTC, dolmen commented on suite/suite_test.go
> +	bytes, err := io.ReadAll(sc.readPipe)
This change requires Go 1.16. `testify` is used in a wide range of project. This is not a good thing to force users to upgrade Go while it is not necessary (`io/ioutil` will stay forever).

2023-07-04 08:31 UTC, dolmen commented
This PR bundles too many unrelated changes with a misleading title. I recommend @testwill to close it and submit more targetted changes and take more care in the description of the PR.

2023-07-05 09:59 UTC, closed without merging