Recover and fail on subtest
stretchr/testify pull request #1455
Opened 2023-08-10 06:54 UTC by anuragprafulla

## Summary

## Changes

## Motivation

## Related issues

2023-08-11 08:34 UTC, dolmen commented
Please spare the time of the maintainers by filling the description properly.

2023-08-11 08:42 UTC, dolmen requested changes

2023-08-11 08:42 UTC, dolmen commented on suite/suite.go
> +		defer recoverAndFailOnPanic(t)
This change needs a matching test case for future regression testing.

2023-08-24 06:08 UTC, xwjdsh commented
@dolmen I submitted [a PR](https://github.com/stretchr/testify/pull/1293) long ago and was just reminded by a reply. I noticed this PR was duplicated with it, could you please take a look #1293?

2023-10-16 15:50 UTC, dolmen commented
@xwjdsh There are changes in #1471 which are about to be merged and are also related to suite subtests. Could you add your review there and tell me if there will be something remaining to fix in #1455 and #1293?

2023-10-30 21:44 UTC, closed without merging

2023-10-30 21:44 UTC, dolmen commented
Closing because this change is included in #1471.