suite: fix deadlock in suite.Require()/Assert()
stretchr/testify pull request #1535
Opened 2024-02-16 19:50 UTC by arjunmahishi

As pointed out in issue #1520, if the suite is not initialised properly (buy calling the Run function), then calling suite.Require() or suite.Assert() will result in a deadlock.

## Changes

This commit fixes that by panicking if the suite is not initialised properly. This is justified because, the suite is intended to be triggered in the right way. If the user does not do that, this panic will nudge them in the right direction.

It has to be a panic because, at this point, we don't have access to any testing.T context to gracefully call a t.Fail(). Also, these two functions are not expected to return an error.

## Related issues

Fixes #1520

2024-02-17 16:12 UTC, brackendawson requested changes
This is a breaking change.

Instead, you can fix the deadlock by making two versions of the `T` method:
```go
// T retrieves the current *testing.T context.
func (suite *Suite) T() *testing.T {
	suite.mu.RLock()
	defer suite.mu.RUnlock()
	return suite._t()
}

func (suite *Suite) _t() *testing.T {
	return suite.t
}
```

And then calling the internal version from `Require` and `Assert`, since they are alreadty protected by the lock.

2024-02-17 18:29 UTC, arjunmahishi commented
> This is a breaking change.

How? This would have never worked in the previous version right?

> You can fix the deadlock by making two versions of the T method

But just like `suite.require`, `suite.t` would also not be initialised without calling `Run`. So, the user would run into a _nil pointer deref_ panic.

```
                                          ┌─────────────────────────────────────────┐ 
                                          │func (suite *Suite) SetT(t *testing.T) { │ 
                                          │  suite.mu.Lock()                        │
┌─────┐        ┌─────────────┐            │  defer suite.mu.Unlock()                │
│Run()├───────►│suite.SetT(t)├───────────►│  suite.t = t                            │
└─────┘        └─────────────┘            │  suite.Assertions = assert.New(t)       │
                                          │  suite.require = require.New(t)         │
                                          │}                                        │ 
                                          └─────────────────────────────────────────┘ 

```

2024-02-18 18:04 UTC, brackendawson commented
At v1.0 (which is difficult to require from a modern module) `SetT` exists and does not initialise `suite.Suite.Require`, and the code path we are modifying was useful, it sucessfully returned a functioning `Require` to this contrived example:
```go
package kata_test

import (
	"os"
	"testing"

	"github.com/stretchr/testify/suite"
)

type mySuite struct {
	suite.Suite
}

func (suite *mySuite) TestSomething() {
	require := suite.Require()
	require.True(true)
}

func TestSuite(t *testing.T) {
	m := &mySuite{}
	m.SetT(t)
	f, err := os.Create("testfile")
	m.Require().NoError(err)
	defer f.Close()
	suite.Run(t, m)
}
```

This code works today because `SetT` also initialises both `suite.Suite.Assert` and `suite.Suite.Require`, meaning we don't traverse the code we're modifying, which has at various times been a nil pointer dereference, a deadlock, or now a deliberate panic.

So I think you are right, I can't contrive an example that is broken by this change, it's not a breaking change.

Perhaps though the panic message should encompass something like: *"Require must not be called before Run or SetT"*.

2024-02-18 18:27 UTC, arjunmahishi commented
Ohh got it. Thanks for the context!
Are you on board with panicking though? (I've changed the message)

2024-02-18 18:34 UTC, brackendawson approved these changes

2024-02-18 18:34 UTC, merged