Lazily render mock diff output on successful match
stretchr/testify pull request #1615
Opened 2024-06-25 16:27 UTC by mikeauclair

## Summary

- For mocks on functions that take complex types as arg, `Sprintf`-ing the `actual` value can be costly. Switch successful matches to use thunks to lazily render their output, and fully avoid rendering their output when there are no differences since we return a constant string in that case anyways

## Changes
- Switch to a string builder for accumulating output for better performance even when we *do* render

## Motivation
- We heavily use mocks at DevotedHealth, and use them frequently in gRPC contexts where we're mocking RPCs that take `<Whatever>Request` structs that are costly to `%v` via `Sprintf`. `Sprintf` showed up as a tangible contributor to runtime performance when profiling some of our heavier tests. The below ~5s cpu time spent on `Sprintf` goes away completely here in one of our exemplar tests

<img width="976" alt="Screenshot 2024-06-25 at 12 16 35 PM" src="https://github.com/DevotedHealth/testify/assets/31651/37a7fe5a-e4e3-4f4d-8cad-07a101983412">

## Related issues

2024-10-30 11:23 UTC, brackendawson commented
This includes the CallerInfo change from #1614

2024-11-23 11:08 UTC, brackendawson requested changes
I've considered and tried a similar approach before when trying to address #1597. It only removes the race from passing tests, though. If it comes with a sizable performance benefit I'm more than happy to lazily render these.

I'd like it to be separated from #1614, they're not dependant on one another, right?

Then there's some changes I'd like around the use of `outputRenderers`. I'm fairly sure the slice isn't even necessary, you can change `actualFmt`'s type from `string` to `func() string` and change all its references to `actualFmt()`.

2024-11-23 18:35 UTC, mikeauclair commented
> I'd like it to be separated from #1614, they're not dependant on one another, right?

I honestly don't remember if they are or are not given how long it's been since I wrote this. I can try to take a pass on cleaning this and the other PR up after next week (short week for thanksgiving in the states)

2024-12-17 18:29 UTC, mikeauclair commented on mock/mock.go
> +	outputRenderers := []outputRenderer{}
Yeah I waffled back and forth on that for a bit. Can definitely simplify every down to `func() string`

2025-03-23 12:58 UTC, brackendawson requested changes
I think if #1693 were merged then this would still offer a performance benefit in finding the closest match when there are no exact matches.

Though, a better approach might be to fully separate finding the first exact match, finding the closest match, then rendering the diff of the closest match. Diff is getting awfully complicated and has a few too many responsibilities.

2025-03-23 12:58 UTC, brackendawson commented on mock/mock.go
> +		i := j
What's the difference between i and j?

2025-03-24 18:14 UTC, mikeauclair commented on mock/mock.go
> +		i := j
We close over the loop variable in the renderers, so this is to avoid the pre-1.22 loopvar behavior issues. Can definitely drop depending on support requirements

2025-03-24 18:21 UTC, brackendawson commented on mock/mock.go
> +		i := j
Ah of course we do. I mistook it for an artefact from the removal of the outer loop. Could you make it into `i := i`? It is legal and I think more clearly communicates to most gophers that you're deliberately re-scoping the variable.

2025-03-24 18:31 UTC, brackendawson approved these changes
I'm happy with the code and I'm happy enough with the approach being a step towards argument matching in Mock.Called with fewer race conditions.

This should make no change to the text output of the library. But due to the frailty of the area of code it touches I'm going to allow a couple of weeks for other maintainers to comment.

2025-05-06 10:20 UTC, merged

2025-05-06 10:20 UTC, brackendawson commented
Thank you for your contribution.

2025-08-27 11:21 UTC, brackendawson commented
This was reverted by #1786 because it did not properly implement lazy rendering when there was more than one expected call. I anticipate that the fix for #643 will properly implement lazy rendering.