mock: in order mock calls
stretchr/testify pull request #1637
Opened 2024-09-06 13:23 UTC by ReyOrtiz

## Summary

Add helper method to declare the order of the mock calls.

## Changes

* add `InOrder(calls ...*Call)` helper method to declare the order of mock calls by calling `NotBefore()`

## Motivation

This is probably the only feature I miss from `gomock`, it is more intuitive and cleaner to declare the order of the mock calls. Probably most cases can be satisfied with this method.

```
InOrder(
	mockedService1.On("TheExampleMethod", 1, 2, 3).Return(4, nil),
	mockedService2.On("TheExampleMethod2", true).Return(),
	mockedService3.On("TheExampleMethod3", "abc", 3).Return(false, nil),
)

```
## Related issues

2024-09-25 14:58 UTC, brackendawson commented
Ah, an earlier issue, I suspect we'll see this a lot from gomock expats over the coming months.

I'm going to close this is a duplicate of #1639. I know this one was first but the other is more in depth. Please do go add your 👍 to it.

2024-09-25 15:00 UTC, brackendawson requested changes
Can we get a unit test, please.

2024-09-25 15:28 UTC, ReyOrtiz commented
unit test added

2024-09-25 15:42 UTC, brackendawson requested changes
Positive and negative tests, nice one. 👍  Just a couple of small comments.

2024-09-25 15:42 UTC, brackendawson commented on mock/mock_test.go
> +	require.Equal(t, []*Call{b, c}, mockedService.ExpectedCalls)
This line is testing the implementation. A cost effective test would only test the behaviour, as you are doing just fine after this line.

If you remove this assertion then we are free to change the implementation of the intended behaviour without breaking the test. It also removes the need to declare `b` and `c`, so the test can be written as `InOrder` is intended to be used.

2024-09-25 15:42 UTC, brackendawson commented on mock/mock.go
> +// InOrder defines the order in which the calls should be made
This could do with a small usage example for the docs.

2024-09-25 15:44 UTC, brackendawson commented on mock/mock_test.go
> +	require.Equal(t, []*Call{b, c}, mockedService.ExpectedCalls)
Also, it's just comparing pointer values. If InOrder did literally nothing then that assertion would still pass.

2024-09-25 15:54 UTC, brackendawson commented on mock/mock.go
> +// InOrder defines the order in which the calls should be made
It's also the order they need to be "satisfied", not the order they need to be called. In the case where they can be called multiple times.

2024-09-25 16:05 UTC, ReyOrtiz commented
Good comments, thanks! Requested changes applied.

2024-09-25 21:25 UTC, brackendawson approved these changes
Looks good to me, should be helpful to all the developers moving from gomock. I'll give some time for other maintainers to review before I merge.

2024-09-26 08:55 UTC, jybp commented
Ah you beat me to it, thanks!

2024-10-02 15:43 UTC, ReyOrtiz commented
Hello, any ETA on merging this PR?

2024-10-02 16:23 UTC, merged

2024-10-02 16:25 UTC, brackendawson commented
Thanks @ReyOrtiz. This can be consumed now by gomock expats with: `go get github.com/stretchr/testify@master`. Once testify v1.10 is released it can be consumed as per the README. I'll have a look at drafting a release soon.

2024-10-02 16:27 UTC, ReyOrtiz commented
Thanks @brackendawson for all the help! 🙏