Update documentation for the Error function in assert or require package #1609
stretchr/testify pull request #1675
Opened 2024-11-02 21:01 UTC by architagr

## Summary
Incorrect assert.Error() docs

## Changes
Removing the if statement and the Equal call from the example.

## Motivation
Since we already have EqualError, the documentation is trying to use `assert.Equal` to assert the error object's content.

## Related issues
Closes #1609

2024-12-10 09:22 UTC, dolmen submitted a review, later dismissed
The change now hides that `Error` returns a boolean that can be used for further checks.

I think that we must keep the if statement around in the usage example.

2024-12-15 16:04 UTC, architagr commented
> The change now hides that `Error` returns a boolean that can be used for further checks.
> 
> I think that we must keep the if statement around in the usage example.

This change is in accordance with the below conversation by @brackendawson

https://github.com/stretchr/testify/issues/1609#issuecomment-2402331089

2024-12-23 11:38 UTC, brackendawson approved these changes
I approve as is.

This was a poor place to document the assert assertions returning a booleans. It's just one assertion out of many. Perhaps one of the examples at the top of the package should be used.

It's important to remove this from the assert.Error doc because it is also used as the require.Error doc, which does not return a boolean! The only alternative is writing some code in the generator to handle it.

I also think the example is a bad example because the inner assert.Equal can stand in place of the entire example.

2024-12-23 11:41 UTC, brackendawson commented on assert/assertions.go
> +//	assert.Error(t, err)
This is not good practice IMO, a good test will check the returned actualObj even if the returned error is non-nil.

2025-03-22 22:24 UTC, brackendawson commented
@architagr I'd like to get this merged but I can't in good faith dismiss @dolmen's review because this PR still removes the last reference to assert's functions returning a bool. Can you add a paragraph to assert/doc.go which explains that all assertions return a bool indicating if the assertion passed? Then I think we can merge this change.

2025-04-22 18:03 UTC, architagr commented
> > @architagr I'd like to get this merged but I can't in good faith dismiss @dolmen's review because this PR still removes the last reference to assert's functions returning a bool. Can you add a paragraph to assert/doc.go which explains that all assertions return a bool indicating if the assertion passed? Then I think we can merge this change.
> 
> Sure I can do that

2025-04-22 18:05 UTC, architagr commented
> @architagr I'd like to get this merged but I can't in good faith dismiss @dolmen's review because this PR still removes the last reference to assert's functions returning a bool. Can you add a paragraph to assert/doc.go which explains that all assertions return a bool indicating if the assertion passed? Then I think we can merge this change.

Hi @brackendawson, I have updated the doc.go, can you please have a look if that looks ok.

2025-04-22 19:13 UTC, ccoVeille commented on assert/doc.go
>  // # Example Usage
Did you check with pkgsite if it was still displaying a header for the example?

Because I would expect the comment to be like this

```suggestion
// All functions in this package return a bool value indicating whether the test has passed.
	//
 // # Example Usage
```

Also please consider using this

```suggestion
//
// # Note
// All functions in this package return a bool value indicating whether the test has passed.
	//
 // # Example Usage
```

Please check for difference by using pkgsite

2025-04-29 13:01 UTC, ccoVeille commented on assert/doc.go
>  // The following is a complete example using assert in a standard test function:
The exact syntax should be this

```suggestion
// Package assert provides a set of comprehensive testing tools for use with the normal Go testing system.
//
// # Note
//
// All functions in this package return a bool value indicating whether the test has passed.
//
// # Example Usage
//
// The following is a complete example using assert in a standard test function:
```

Here is the difference of rendering with and without the empty line of comments

![image](https://github.com/user-attachments/assets/0ea3a06c-f1bd-4d61-bb52-592df82f7669)

![image](https://github.com/user-attachments/assets/225ffb9a-89f7-4422-a60a-66e1a398acaf)

2025-05-02 07:56 UTC, ccoVeille submitted a review, later dismissed

2025-05-06 10:29 UTC, brackendawson requested changes
Looks good and renders fine in pkgsite.

2025-05-06 10:29 UTC, brackendawson commented on assert/doc.go
> +// All functions in this package return a bool value indicating whether the test has passed.
```suggestion
// All functions in this package return a bool value indicating whether the assertion has passed.
```

We shouldn't say "test" here because Go's testing package defines the test as the test function.

2025-05-07 12:53 UTC, brackendawson approved these changes
LGTM, thank you for your contribution. And thank you to the other maintainers for your diligent reviews.

2025-05-07 12:56 UTC, merged