Improve ErrorIs message when error is nil but an error was expected
stretchr/testify pull request #1681
Opened 2024-11-18 12:14 UTC by tsioftas

## Summary
This improves the UX of users of `ErrorIs()` in case the value `nil` is passed for `err` while an error was expected.

## Changes
- added check if `err == nil && target != nil` -> return a special error-string 
- updated relevant test case

## Motivation
The error message when an error is expected but `err` is `nil` (a common occurence in the world of testing) could be more helpful, e.g.:
```
(before)
some_test.go:20:
                Error Trace:    /[...]/some_test.go:20
                Error:          Target error should be in err chain:
                                expected: "sample error message"
                                in chain:
```
vs
```
(after)
some_test.go:20:
                Error Trace:    /[...]/some_test.go:20
                Error:          Expected error "sample error message" but got nil.
```

2024-11-20 19:18 UTC, ccoVeille approved these changes

2025-03-23 13:42 UTC, brackendawson requested changes

2025-03-23 13:42 UTC, brackendawson commented on assert/assertions_test.go
> +			resultErrMsg: "Expected error \"EOF\" but got nil.\n",
A bit more concise
```suggestion
			resultErrMsg: "Expected error with \"EOF\" in chain but got nil.\n",
```

2025-05-08 10:40 UTC, brackendawson approved these changes
LGTM, thank you for your contribution.

2025-05-08 10:40 UTC, merged

2025-05-08 11:00 UTC, ccoVeille commented
Thanks for this change.

It would be way clearer.