docs: Format examples in README
stretchr/testify pull request #1687
Opened 2024-12-16 20:30 UTC by alexandear

## Summary

Format Go code in the README with `gofmt` and remove empty lines.

## Changes

- Replace spaces with tabs.
- Add empty lines between imports.
- Remove empty lines in blocks.

## Motivation

The code should be formatted the same as `gofmt` even in the documentation.

2025-01-07 10:34 UTC, dolmen commented
It would be helpful to have a CI test that ensures this remains in the future. Any pointer to such a tool that would extract blocks of `go` code from a Markdown document and report diffs?

2025-01-07 10:36 UTC, dolmen submitted a review, later dismissed

2025-01-07 12:12 UTC, ccoVeille commented
I'm using mdsf for formatting fenced blocks in Markdown files.

https://github.com/hougesen/mdsf

2025-01-20 17:51 UTC, alexandear commented
> It would be helpful to have a CI test that ensures this remains in the future. Any pointer to such a tool that would extract blocks of `go` code from a Markdown document and report diffs?

Integrated [hougesen/mdsf](https://github.com/hougesen/mdsf) as @ccoVeille suggested.

2025-01-20 17:58 UTC, ccoVeille commented
CC: @hougesen

2025-01-20 18:01 UTC, ccoVeille approved these changes

2025-03-22 21:44 UTC, brackendawson requested changes

2025-03-22 21:44 UTC, brackendawson commented on .github/workflows/main.yml
> +      - run: ./.ci.readme.fmt.sh
Does this directly call the gofmt tool? If so then this should be under the jobs.build key so that it always runs with the version/s of go whose format we target.

2025-03-23 10:42 UTC, alexandear commented on .github/workflows/main.yml
> +      - run: ./.ci.readme.fmt.sh
Moved to `jobs.build`

2025-03-23 11:08 UTC, brackendawson approved these changes
LGTM. I don't even have to install npm, just gotta' format things right.

2025-03-23 11:09 UTC, merged