Add prefix and suffix assertions
stretchr/testify pull request #629
Opened 2018-07-09 20:22 UTC by georgelesica-wf

I found myself wanting to make assertions about string and slice prefixes and suffixes so I thought these might make sense for others as well.

I modeled the new assertions off of the existing `Contains` assertion, but I am open to changing it if the maintainers have other preferences.

2018-07-10 18:06 UTC, georgelesica-wf commented
@ernesto-jimenez I can't seem to get the code generation to work in all versions of Go, even on master, any thoughts?

2018-07-11 12:47 UTC, hekonsek commented
+1 for this PR :)

2018-07-12 21:45 UTC, georgelesica-wf commented
It looks like this will fix the issue failing CI for this PR https://github.com/stretchr/testify/pull/620

2019-04-29 09:33 UTC, systay commented
Another +1 for this addition

2023-07-31 18:18 UTC, dolmen commented
@georgelesica-wf Please rebase. The code can't be reviewed in this state.

2023-07-31 18:19 UTC, dolmen reviewed
Code must be rebased before review.

2024-03-28 22:27 UTC, dolmen requested changes
Too many irrelevant changes in this PR: changing the codegen system should be separated from changes adding new features.

2024-03-28 22:27 UTC, dolmen commented on .gitignore
> +
This change should not be bundled in this PR.

2024-03-28 22:27 UTC, dolmen commented on .travis.gofmt.sh
> +
This change should not be bundled in this PR.

2024-03-28 22:27 UTC, dolmen commented on .travis.gogenerate.sh
> +echo ".travis.gogenerate.sh"
This change should not be bundled in this PR.

2026-05-12 10:20 UTC, dolmen commented
Too old to be able to rebase. Closing.

2026-05-12 10:20 UTC, closed without merging